// Code generated by MockGen. DO NOT EDIT.
// Source: delayednotifier/internal/service (interfaces: NotificationSender)
//
// Generated by this command:
//
//	mockgen -package=mock_sender -destination=internal/transport/sender/mock/sender_mock.go delayednotifier/internal/service NotificationSender
//

// Package mock_sender is a generated GoMock package.
package mock_sender

import (
	context "context"
	entity "delayednotifier/internal/entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockNotificationSender is a mock of NotificationSender interface.
type MockNotificationSender struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationSenderMockRecorder
	isgomock struct{}
}

// MockNotificationSenderMockRecorder is the mock recorder for MockNotificationSender.
type MockNotificationSenderMockRecorder struct {
	mock *MockNotificationSender
}

// NewMockNotificationSender creates a new mock instance.
func NewMockNotificationSender(ctrl *gomock.Controller) *MockNotificationSender {
	mock := &MockNotificationSender{ctrl: ctrl}
	mock.recorder = &MockNotificationSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationSender) EXPECT() *MockNotificationSenderMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockNotificationSender) Send(ctx context.Context, notification entity.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, notification)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockNotificationSenderMockRecorder) Send(ctx, notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockNotificationSender)(nil).Send), ctx, notification)
}
