// Code generated by MockGen. DO NOT EDIT.
// Source: delayednotifier/internal/service (interfaces: CacheRepository)
//
// Generated by this command:
//
//	mockgen -package=mock_repository -destination=internal/repository/mock/cache_repository_mock.go delayednotifier/internal/service CacheRepository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	entity "delayednotifier/internal/entity"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCacheRepository is a mock of CacheRepository interface.
type MockCacheRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCacheRepositoryMockRecorder
	isgomock struct{}
}

// MockCacheRepositoryMockRecorder is the mock recorder for MockCacheRepository.
type MockCacheRepositoryMockRecorder struct {
	mock *MockCacheRepository
}

// NewMockCacheRepository creates a new mock instance.
func NewMockCacheRepository(ctrl *gomock.Controller) *MockCacheRepository {
	mock := &MockCacheRepository{ctrl: ctrl}
	mock.recorder = &MockCacheRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheRepository) EXPECT() *MockCacheRepositoryMockRecorder {
	return m.recorder
}

// GetCacheKey mocks base method.
func (m *MockCacheRepository) GetCacheKey(id uuid.UUID) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCacheKey", id)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetCacheKey indicates an expected call of GetCacheKey.
func (mr *MockCacheRepositoryMockRecorder) GetCacheKey(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCacheKey", reflect.TypeOf((*MockCacheRepository)(nil).GetCacheKey), id)
}

// GetFromCache mocks base method.
func (m *MockCacheRepository) GetFromCache(ctx context.Context, key string) (*entity.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFromCache", ctx, key)
	ret0, _ := ret[0].(*entity.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFromCache indicates an expected call of GetFromCache.
func (mr *MockCacheRepositoryMockRecorder) GetFromCache(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFromCache", reflect.TypeOf((*MockCacheRepository)(nil).GetFromCache), ctx, key)
}

// InvalidateCache mocks base method.
func (m *MockCacheRepository) InvalidateCache(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateCache", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateCache indicates an expected call of InvalidateCache.
func (mr *MockCacheRepositoryMockRecorder) InvalidateCache(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateCache", reflect.TypeOf((*MockCacheRepository)(nil).InvalidateCache), ctx, id)
}

// SaveToCache mocks base method.
func (m *MockCacheRepository) SaveToCache(ctx context.Context, key string, notification *entity.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveToCache", ctx, key, notification)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveToCache indicates an expected call of SaveToCache.
func (mr *MockCacheRepositoryMockRecorder) SaveToCache(ctx, key, notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveToCache", reflect.TypeOf((*MockCacheRepository)(nil).SaveToCache), ctx, key, notification)
}
