// Code generated by MockGen. DO NOT EDIT.
// Source: delayednotifier/internal/service (interfaces: NotifyRepository)
//
// Generated by this command:
//
//	mockgen -package=mock_repository -destination=internal/repository/mock/notify_repository_mock.go delayednotifier/internal/service NotifyRepository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	entity "delayednotifier/internal/entity"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	pgxdriver "github.com/wb-go/wbf/dbpg/pgx-driver"
	gomock "go.uber.org/mock/gomock"
)

// MockNotifyRepository is a mock of NotifyRepository interface.
type MockNotifyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNotifyRepositoryMockRecorder
	isgomock struct{}
}

// MockNotifyRepositoryMockRecorder is the mock recorder for MockNotifyRepository.
type MockNotifyRepositoryMockRecorder struct {
	mock *MockNotifyRepository
}

// NewMockNotifyRepository creates a new mock instance.
func NewMockNotifyRepository(ctrl *gomock.Controller) *MockNotifyRepository {
	mock := &MockNotifyRepository{ctrl: ctrl}
	mock.recorder = &MockNotifyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifyRepository) EXPECT() *MockNotifyRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNotifyRepository) Create(ctx context.Context, qe pgxdriver.QueryExecuter, notify entity.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, qe, notify)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockNotifyRepositoryMockRecorder) Create(ctx, qe, notify any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNotifyRepository)(nil).Create), ctx, qe, notify)
}

// GetByID mocks base method.
func (m *MockNotifyRepository) GetByID(ctx context.Context, qe pgxdriver.QueryExecuter, id uuid.UUID, forUpdate bool) (*entity.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, qe, id, forUpdate)
	ret0, _ := ret[0].(*entity.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockNotifyRepositoryMockRecorder) GetByID(ctx, qe, id, forUpdate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockNotifyRepository)(nil).GetByID), ctx, qe, id, forUpdate)
}

// GetForProcess mocks base method.
func (m *MockNotifyRepository) GetForProcess(ctx context.Context, qe pgxdriver.QueryExecuter, limit uint64) ([]entity.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetForProcess", ctx, qe, limit)
	ret0, _ := ret[0].([]entity.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetForProcess indicates an expected call of GetForProcess.
func (mr *MockNotifyRepositoryMockRecorder) GetForProcess(ctx, qe, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetForProcess", reflect.TypeOf((*MockNotifyRepository)(nil).GetForProcess), ctx, qe, limit)
}

// RescheduleNotification mocks base method.
func (m *MockNotifyRepository) RescheduleNotification(ctx context.Context, qe pgxdriver.QueryExecuter, id uuid.UUID, newScheduledAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RescheduleNotification", ctx, qe, id, newScheduledAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// RescheduleNotification indicates an expected call of RescheduleNotification.
func (mr *MockNotifyRepositoryMockRecorder) RescheduleNotification(ctx, qe, id, newScheduledAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RescheduleNotification", reflect.TypeOf((*MockNotifyRepository)(nil).RescheduleNotification), ctx, qe, id, newScheduledAt)
}

// UpdateStatus mocks base method.
func (m *MockNotifyRepository) UpdateStatus(ctx context.Context, qe pgxdriver.QueryExecuter, id uuid.UUID, status entity.Status, lastErr *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, qe, id, status, lastErr)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockNotifyRepositoryMockRecorder) UpdateStatus(ctx, qe, id, status, lastErr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockNotifyRepository)(nil).UpdateStatus), ctx, qe, id, status, lastErr)
}
