// Code generated by MockGen. DO NOT EDIT.
// Source: delayednotifier/internal/service (interfaces: TelegramRepository)
//
// Generated by this command:
//
//	mockgen -package=mock_repository -destination=internal/repository/mock/telegram_repository_mock.go delayednotifier/internal/service TelegramRepository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTelegramRepository is a mock of TelegramRepository interface.
type MockTelegramRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTelegramRepositoryMockRecorder
	isgomock struct{}
}

// MockTelegramRepositoryMockRecorder is the mock recorder for MockTelegramRepository.
type MockTelegramRepositoryMockRecorder struct {
	mock *MockTelegramRepository
}

// NewMockTelegramRepository creates a new mock instance.
func NewMockTelegramRepository(ctrl *gomock.Controller) *MockTelegramRepository {
	mock := &MockTelegramRepository{ctrl: ctrl}
	mock.recorder = &MockTelegramRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTelegramRepository) EXPECT() *MockTelegramRepositoryMockRecorder {
	return m.recorder
}

// GetChatID mocks base method.
func (m *MockTelegramRepository) GetChatID(ctx context.Context, username string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatID", ctx, username)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatID indicates an expected call of GetChatID.
func (mr *MockTelegramRepositoryMockRecorder) GetChatID(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatID", reflect.TypeOf((*MockTelegramRepository)(nil).GetChatID), ctx, username)
}

// SaveSubscriber mocks base method.
func (m *MockTelegramRepository) SaveSubscriber(ctx context.Context, username string, chatID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSubscriber", ctx, username, chatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSubscriber indicates an expected call of SaveSubscriber.
func (mr *MockTelegramRepositoryMockRecorder) SaveSubscriber(ctx, username, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSubscriber", reflect.TypeOf((*MockTelegramRepository)(nil).SaveSubscriber), ctx, username, chatID)
}
