// Code generated by MockGen. DO NOT EDIT.
// Source: delayednotifier/internal/service (interfaces: UserRepository)
//
// Generated by this command:
//
//	mockgen -package=mock_repository -destination=internal/repository/mock/user_repository_mock.go delayednotifier/internal/service UserRepository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	pgxdriver "github.com/wb-go/wbf/dbpg/pgx-driver"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// GetEmail mocks base method.
func (m *MockUserRepository) GetEmail(ctx context.Context, qe pgxdriver.QueryExecuter, userID uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmail", ctx, qe, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmail indicates an expected call of GetEmail.
func (mr *MockUserRepositoryMockRecorder) GetEmail(ctx, qe, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmail", reflect.TypeOf((*MockUserRepository)(nil).GetEmail), ctx, qe, userID)
}

// GetTelegramChatID mocks base method.
func (m *MockUserRepository) GetTelegramChatID(ctx context.Context, qe pgxdriver.QueryExecuter, userID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTelegramChatID", ctx, qe, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTelegramChatID indicates an expected call of GetTelegramChatID.
func (mr *MockUserRepositoryMockRecorder) GetTelegramChatID(ctx, qe, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTelegramChatID", reflect.TypeOf((*MockUserRepository)(nil).GetTelegramChatID), ctx, qe, userID)
}
